import { writeFile, readdir } from "fs/promises";
import { join, basename } from "path";
import chalk from "chalk";
import type { ArchdocConfig } from "../types/config.js";
import type { WikiPage } from "../types/wiki.js";
import type { WikiManifest, ManifestPage, ManifestArtifact, ManifestHarvestTool } from "../types/wiki.js";
import type { HarvestBag } from "../types/tool.js";

export async function runAssemble(
  config: ArchdocConfig,
  pages: WikiPage[],
  outputDir: string,
  bag?: HarvestBag
): Promise<void> {
  const sorted = [...pages].sort((a, b) => a.frontmatter.order - b.frontmatter.order);

  // Write markdown pages
  for (const page of sorted) {
    const filename = `${page.frontmatter.slug}.md`;
    const content = serializePage(page);
    await writeFile(join(outputDir, filename), content);
    console.log(chalk.dim(`  ✓ ${filename}`));
  }

  // Write index page
  const index = generateIndex(sorted);
  await writeFile(join(outputDir, "index.md"), index);
  console.log(chalk.dim("  ✓ index.md"));

  // Write manifest
  const manifest = await buildManifest(config, sorted, outputDir, bag);
  await writeFile(join(outputDir, "manifest.json"), JSON.stringify(manifest, null, 2));
  console.log(chalk.dim("  ✓ manifest.json"));
}

function serializePage(page: WikiPage): string {
  const fm = page.frontmatter;
  const frontmatter = [
    "---",
    `title: "${fm.title}"`,
    `slug: ${fm.slug}`,
    `order: ${fm.order}`,
    `tags: [${fm.tags.map((t) => `"${t}"`).join(", ")}]`,
    `cross_refs: [${fm.crossRefs.map((r) => `"${r}"`).join(", ")}]`,
    "---",
  ].join("\n");

  return `${frontmatter}\n\n${page.content}\n`;
}

function generateIndex(pages: WikiPage[]): string {
  const lines = [
    "# archdoc Wiki",
    "",
    "## Pages",
    "",
  ];

  for (const page of pages) {
    lines.push(`- [${page.frontmatter.title}](./${page.frontmatter.slug}.md)`);
  }

  lines.push("");
  lines.push(`*Generated by archdoc on ${new Date().toISOString().slice(0, 10)}*`);
  lines.push("");

  return lines.join("\n");
}

async function buildManifest(
  config: ArchdocConfig,
  pages: WikiPage[],
  outputDir: string,
  bag?: HarvestBag
): Promise<WikiManifest> {
  const repoName = basename(config.targetPath);
  const now = new Date().toISOString();

  // Pages
  const manifestPages: ManifestPage[] = pages.map((p) => ({
    title: p.frontmatter.title,
    slug: p.frontmatter.slug,
    file: `${p.frontmatter.slug}.md`,
    order: p.frontmatter.order,
    tags: p.frontmatter.tags,
    crossRefs: p.frontmatter.crossRefs,
  }));

  // Collect all unique tags
  const allTags = [...new Set(pages.flatMap((p) => p.frontmatter.tags))].sort();

  // Artifacts — scan output dir for non-markdown files that enrich steps may produce
  const artifacts: ManifestArtifact[] = [];
  try {
    const files = await readdir(outputDir);
    for (const file of files) {
      if (file.endsWith(".html") && file !== "index.html") {
        artifacts.push({
          id: file.replace(/\.html$/, ""),
          file,
          type: "html",
          description: inferArtifactDescription(file),
        });
      } else if (file.endsWith(".json") && file !== "manifest.json" && file !== "harvest-bag.json") {
        artifacts.push({
          id: file.replace(/\.json$/, ""),
          file,
          type: "json",
          description: inferArtifactDescription(file),
        });
      }
    }
  } catch {
    // Output dir might not have artifacts yet on first run
  }

  // Harvest tool results
  const harvest: ManifestHarvestTool[] = [];
  if (bag) {
    for (const [toolId, meta] of Object.entries(bag.resultMeta)) {
      harvest.push({
        id: toolId,
        status: meta.status,
        file: meta.status === "success" ? `${toolId}.json` : null,
        durationMs: meta.status === "success" ? meta.durationMs : null,
      });
    }
  }

  return {
    version: 1,
    repo: repoName,
    targetPath: config.targetPath,
    generatedAt: now,
    harvestedAt: bag?.harvestedAt ?? now,
    pages: manifestPages,
    artifacts,
    harvest,
    tags: allTags,
  };
}

function inferArtifactDescription(filename: string): string {
  if (filename.includes("test-intent-map") && filename.endsWith(".html")) {
    return "Interactive test intent map report";
  }
  if (filename.includes("test-intent-map") && filename.endsWith(".json")) {
    return "Classified test data with types and intent annotations";
  }
  return filename;
}
